FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
# jjj
ARG PORT
ARG MONGO_URI
ARG GMAIL_USERNAME
ARG GMAIL_PASSWORD
ARG JWT_SECRET

ENV PORT=${PORT}
ENV MONGO_URI=${MONGO_URI}
ENV GMAIL_USERNAME=${GMAIL_USERNAME}
ENV GMAIL_PASSWORD=${GMAIL_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE ${PORT}

CMD ["npm", "start"]